
name: 'set pull request title'
description: 'sets the title of a pull request to the given value'
author: 'Joost Somers'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  github-token:
    description: 'token of your github'
    required: true
  pr-title:
    description: 'PR title'
    required: true
